# $HOME/.config/helix/config.toml

theme = "catppuccin_mocha"

[editor]
line-number = "absolute"
mouse = false
cursorline = true
color-modes = true
auto-save = false
bufferline = "multiple"
true-color = true
rulers = [121]
text-width = 120

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "register", "position", "file-encoding"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = false
auto-signature-help = true
display-signature-help-docs = true

[editor.indent-guides]
render = true
character = "│"

[editor.soft-wrap]
enable = false
wrap-at-text-width = true
max-wrap = 25
max-indent-retain = 40

[keys.normal]
# Jumplist navigation with Alt+,/. and Alt+</>
"A-," = "jump_backward"
"A-." = "jump_forward"
"A-<" = "jump_backward"
"A->" = "jump_forward"
# Move up/down 5 lines
C-u = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
C-d = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
# Disable arrow keys
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.insert]
# Disable arrow keys
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.select]
# Extend up/down 5 lines
C-u = ["extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up"]
C-d = ["extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down"]
# Disable arrow keys
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
