# $HOME/.config/helix/languages.toml

# Language-specific settings

[language-server.typos-lsp]
command = "typos-lsp"

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }
language-servers = ["typos-lsp", "rust-analyzer"]

[[language]]
name = "python"
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["typos-lsp", "pyright"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
nodePath = ""
onIgnoredFiles = "off"
packageManager = "npm"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
workingDirectory = { mode = "auto" }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript", "--print-width", "120"] }
language-servers = ["typos-lsp", "typescript-language-server", "eslint"]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript", "--print-width", "120"] }
language-servers = ["typos-lsp", "typescript-language-server", "eslint"]

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript", "--print-width", "120"] }
language-servers = ["typos-lsp", "typescript-language-server", "eslint"]

[[language]]
name = "jsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript", "--print-width", "120"] }
language-servers = ["typos-lsp", "typescript-language-server", "eslint"]

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json", "--print-width", "120"] }
language-servers = ["typos-lsp"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["typos-lsp"]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown", "--print-width", "120", "--prose-wrap", "always"] }
language-servers = ["typos-lsp"]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml", "--print-width", "120", "--prose-wrap", "always"] }
language-servers = ["typos-lsp"]
